Add support for eggs
ftpsolutions/python-third-party-license-file-generator pull request #7
Opened 2020-08-14 14:06 UTC by andzn

Currently if any python packages are installed as eggs, the tool doesn't detect any licenses for them.
This change adds support for reading licenses of python packages that are installed as eggs.

2020-08-17 09:07 UTC, andzn commented
@lowaa could you please take a look over the changes? It seems I'm not able to add reviewers after I created the PR, that's why I ping you via comment.

2020-08-18 02:32 UTC, initialed85 requested changes

2020-08-18 02:32 UTC, initialed85 commented on third_party_license_file_generator/site_packages.py
>                  continue
```suggestion
                	continue
```

Syntax error here- Tabbing in `continue` will solve it.

2020-08-18 02:33 UTC, initialed85 requested changes
If you can fix up the syntax error: re the indentation for `continue` then I think it's all good.

After manually fixing that, I tested:

- using 2.7 venv
	- against a real 2.7 venv
	- against a real 3.7 venv
- using 3.7 venv
	- against a real 2.7 venv
	- against a real 3.7 venv

But please note I didn't test the egg path (so I've basically just confirmed that no existing behaviour has been broken).

If the egg path works for you then we're laughing!

2020-08-18 07:38 UTC, initialed85 approved these changes
```
       👍 👍 
       👍 👍 
     👍 👍 👍 👍 
👍 👍 👍 👍 👍 👍 
👍 👍 👍 👍 👍 👍 
👍 👍 👍 👍 👍 👍 
👍 👍 👍 👍 👍 👍 
     👍 👍 👍 
```

I'll do a release shortly

EDIT: Stupid formatting messing with my thumbs up made of thumbs ups

EDIT EDIT: Thumbs up fixed

2020-08-18 07:43 UTC, merged

2020-08-18 07:56 UTC, andzn commented
Thanks a lot @initialed85 !